dubbo:
  application:
    name: dubbo-springboot-demo-provider
    # 注册模式，all、instance（应用级别）、interface（接口级别）
    register-mode: instance
  protocol:
    # 协议名称，dubbo、tri（triple）
    # 注意：使用tri协议的时候，pom.xml要导入对应的依赖
    name: tri
    port: -1
  registry:
    id: zk-registry
    address: zookeeper://127.0.0.1:2181
  config-center:
    address: zookeeper://127.0.0.1:2181
  metadata-report:
    address: zookeeper://127.0.0.1:2181